const mongoose = require("mongoose");

// const userSchema = new mongoose.Schema({
//   firstName: { type: String },
//   lastName: { type: String },
//   prefName: { type: String },
//   jobTitle: { type: String },
//   department: { type: String },
//   directReports: { type: [mongoose.Schema.Types.ObjectId], default: [] },
//   division: { type: String, default: null },
//   email: { type: String },
//   location: { type: String },
//   imgUrl: { type: String },
//   reportsTo: { type: mongoose.Schema.Types.ObjectId, default: null },
//   workPhone: { type: String, default: null },
//   ext: { type: String, default: null },
//   personalPhone: { type: String, default: null },
//   id: { type: Number },
//   linkedInUrl: { type: String, default: null },
//   twitterUrl: { type: String, default: null },
//   facebookUrl: { type: String, default: null },
//   instagramUrl: { type: String, default: null },
//   timeOff: { type: String, default: null },
//   timeOffIcon: { type: String, default: null },
//   skype: { type: String, default: null },
//   pinterest: { type: String, default: null },
//   pronouns: { type: String, default: null },
//   canUploadPhoto: { type: Boolean, default: null },
//   photoUploaded: { type: Boolean, default: null },
//   timezone: { type: String },
//   __v: { type: Number, default: 0 },
// });

const userSchema = new mongoose.Schema({
  firstName: { type: String, default: null },
  lastName: { type: String, default: null },
  prefName: { type: String, default: null },
  jobTitle: { type: String, default: null },
  department: { type: String, default: null },
  directReports: { type: [String], default: [] },
  division: { type: String, default: null },
  email: { type: String, default: null },
  location: { type: String, default: null },
  imgUrl: { type: String, default: null },
  reportsTo: { type: String, default: null },
  workPhone: { type: String, default: null },
  ext: { type: String, default: null },
  personalPhone: { type: String, default: null },
  id: { type: Number, default: null },
  linkedInUrl: { type: String, default: null },
  twitterUrl: { type: String, default: null },
  facebookUrl: { type: String, default: null },
  instagramUrl: { type: String, default: null },
  timeOff: { type: String, default: null },
  timeOffIcon: { type: String, default: null },
  skype: { type: String, default: null },
  pinterest: { type: String, default: null },
  pronouns: { type: String, default: null },
  canUploadPhoto: { type: Boolean, default: null },
  photoUploaded: { type: Boolean, default: null },
  timezone: { type: String, default: null },
});

const GDUser = mongoose.model("gduser", userSchema);

module.exports = GDUser;
